lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 360000
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
    api_platform:
        check_path: /auth
        username_path: email
        password_path: password
